# Generated by Django 4.0.3 on 2022-05-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AddField(
            model_name='bankbookkk',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
