# Generated by Django 4.0.3 on 2022-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_transaction_options_bankbookkk_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbookkk',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Sổ đã đóng hay chưa?'),
        ),
    ]
