# Generated by Django 4.0.3 on 2022-06-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_bankbookkk_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbookkk',
            name='balance',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Email khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Số điện thoại khách hàng'),
        ),
    ]
