# Generated by Django 4.0.3 on 2022-06-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_bankbookkk_balance_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='identityid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CMND/CCCD'),
        ),
    ]
