# Generated by Django 4.0.3 on 2022-05-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_bankbookkktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbookkk',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bankbookkktype'),
        ),
    ]
