# Generated by Django 4.0.3 on 2022-05-26 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bankbookkk_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbookkk',
            name='type',
        ),
        migrations.AlterField(
            model_name='bankbookkk',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bankbookkktype', verbose_name='Loại tiết kiệm'),
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Interest rate from 0 - 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tỷ lệ lãi suất'),
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Tên loại tiết kiệm'),
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='period',
            field=models.PositiveSmallIntegerField(help_text='BankBook period', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Độ dài kỳ hạn (0 tương ứng với Không kỳ hạn)'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bankbookkk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bankbookkk')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
