# Generated by Django 4.0.3 on 2022-05-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_bankbookkk_type_alter_bankbookkk_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbookkktype',
            name='maximum_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bankbookkktype',
            name='minimum_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12, verbose_name='Số tiền gửi tối thiểu'),
        ),
        migrations.AddField(
            model_name='bankbookkktype',
            name='minimum_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
