# Generated by Django 3.1.8 on 2022-05-26 03:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_bankbookkktype_maximum_withdrawal_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Tên khách hàng'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositamount',
            field=models.DecimalField(decimal_places=2, default=0.0009891196834817012, max_digits=12, verbose_name='Số tiền gửi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdrawalamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền rút'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Tỷ lệ từ 0 - 100%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tỷ lệ lãi suất'),
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='maximum_withdrawal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sẽ được hiệu chỉnh sau', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='minimum_withdrawal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sẽ được hiệu chỉnh sau', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bankbookkktype',
            name='period',
            field=models.PositiveSmallIntegerField(help_text='Độ dài là 0 tương ứng với Không kỳ hạn', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Độ dài kỳ hạn '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bankbookkk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bankbookkk', verbose_name='Mã sổ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
