# Generated by Django 4.0.3 on 2022-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_products_category_bankbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
