# Generated by Django 4.0.3 on 2022-05-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbook',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bankbook',
            old_name='name',
            new_name='bookid',
        ),
    ]
