# Generated by Django 4.0.3 on 2022-05-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_price_bankbook_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbook',
            name='customer_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='bankbook',
            name='customer_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Tên khách hàng'),
        ),
        migrations.AddField(
            model_name='bankbook',
            name='firstdeposit',
            field=models.FloatField(null=True, verbose_name='Số tiền gửi'),
        ),
        migrations.AddField(
            model_name='bankbook',
            name='identityid',
            field=models.CharField(max_length=200, null=True, verbose_name='CMND/CCCD'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='bookid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='type',
            field=models.CharField(choices=[('3 tháng', '3 tháng'), ('6 tháng', '6 tháng'), ('Không kỳ hạn', 'Không kỳ hạn')], max_length=200, null=True, verbose_name='Loại tiết kiệm'),
        ),
    ]
