# Generated by Django 4.0.3 on 2022-05-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_bankbook_customer_address_bankbook_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbook',
            name='amount',
        ),
        migrations.AddField(
            model_name='bankbook',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
